name: CI

on: [push]

env:
  RUST_VERSION: stable
  CARGO_INCREMENTAL: 0
  RUSTUP_MAX_RETRIES: 10
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Divvun CI
      uses: divvun/actions/setup@master
      with:
        key: ${{ secrets.DIVVUN_KEY }}
    - name: Get version
      id: version
      uses: divvun/actions/version@master
      with:
        cargo: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install build dependencies
      uses: divvun/actions/pahkat/init@master
      with:
        repo: https://pahkat.uit.no/devtools/
        channel: nightly
        packages: pahkat-uploader
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt
        target: i686-pc-windows-msvc
    - name: Build dotnet5-webinst.exe
      run: |
        cargo build --release --target i686-pc-windows-msvc
      env:
        RUSTC_BOOTSTRAP: 1
    - name: Create dist
      run: |
        mkdir -p dist/bin
        mv target/i686-pc-windows-msvc/release/dotnet5-webinst.exe dist/bin/dotnet5-webinst.exe
    - name: Sign code
      uses: divvun/actions/codesign@master
      with:
        path: dist/bin/dotnet5-webinst.exe
    - name: Create tarball package
      id: package
      uses: divvun/actions/create-txz@master
      with:
        path: dist
    - name: Deploy (dotnet-webinst)
      uses: divvun/actions/deploy@master
      with:
        package-id: dotnet5-webinst
        type: TarballPackage
        platform: windows
        version: ${{ steps.version.outputs.version }}
        payload-path: ${{ steps.package.outputs['txz-path'] }}
        repo: https://pahkat.thetc.se/devtools/
        channel: ${{ steps.version.outputs.channel }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
